import type { Difficulty, FollowUp, Problem, ProblemKind } from './types'

export type MockSection = {
  id: string
  title: string
  countLabel: string
  problems: Problem[]
}

function q(p: {
  id: string
  title: string
  difficulty?: Difficulty
  kind: ProblemKind
  prompt: string
  think: string[]
  solution: string
  explanation: string
  internals?: string
  testing?: string
  pitfalls?: string
  alternatives?: string
  tradeoffs: string
  followups: FollowUp[]
  teaches: string[]
}): Problem {
  return {
    ...p,
    difficulty: p.difficulty ?? 'Senior',
    internals:
      p.internals ??
      'See the solution — the interesting behaviour is in the ownership, isolation, or control flow already described.',
    testing: p.testing ?? 'Write the smallest fake that can force the failure, then the success. No network, no sleep.',
    pitfalls:
      p.pitfalls ??
      'Treating the symptom in the view while the lifetime, race, or boundary stays in the model.',
    alternatives:
      p.alternatives ??
      'Other APIs can work; the constraint (lifetime, single-flight, identity, seam) must still hold.',
  }
}

const swift: Problem[] = [
  q({
    id: 'm-sw-1',
    title: 'Predict the printed values',
    kind: 'Predict',
    prompt: `\`\`\`swift
class Box { var n = 0 }
struct Wrap { var box: Box }
var a = Wrap(box: Box())
var b = a
b.box.n = 1
print(a.box.n)
b.box = Box()
b.box.n = 2
print(a.box.n)
\`\`\`
What prints, and why?`,
    think: ['Is Wrap a value type?', 'Does assigning Wrap copy the class instance?', 'When does \`b.box = Box()\` detach?'],
    solution: `Prints \`1\` then \`1\`. First mutation is through a shared class instance. Second assigns a new Box to \`b\` only; \`a\` still holds the original (n = 1).`,
    explanation: `Structs copy fields. A field that is a class copies the **reference**. This is the COW lesson without a buffer: value type wrapping a reference is still shared mutation until you replace the reference.`,
    internals: `\`var b = a\` copies the Wrap bits (the pointer). No COW unless Wrap implements it.`,
    tradeoffs: 'Wrapping classes in structs without COW is a footgun in models. Fine for a handle type if mutation is intentional.',
    followups: [
      { q: 'How would you get value semantics?', a: 'Copy the Box on mutation (COW) or store Int directly.' },
      { q: 'What if Box were a struct?', a: 'Both prints 0 then a stays 0; b is independent.' },
    ],
    teaches: ['Struct copy', 'Nested references', 'COW vs accidental sharing'],
  }),
  q({
    id: 'm-sw-2',
    title: 'Protocol extension vs witness',
    kind: 'Predict',
    difficulty: 'Advanced',
    prompt: `\`P\` has \`foo()\` in an extension. \`C: P\` reimplements \`foo()\`. Call site is \`let p: any P = C(); p.foo()\`. What runs? What if \`foo\` is a protocol requirement?`,
    think: ['Is foo a requirement?', 'Existential dispatch vs static'],
    solution: `If \`foo\` is **only** in the extension, \`P.foo\` runs (static). If it is a requirement, \`C.foo\` runs (witness).`,
    explanation: 'Same trap as Day 1 logging. Seniors mention the requirement table, not "Swift is dynamic."',
    internals: 'Witness table exists for requirements. Extension methods are committed at the call’s static type.',
    tradeoffs: 'Default implementations on requirements are powerful and surprising. Prefer requirements for overridable behaviour.',
    followups: [{ q: 'some P vs any P?', a: 'Opaque type still uses the witness for requirements; it just hides the concrete type.' }],
    teaches: ['Witness tables', 'some vs any', 'Default implementations'],
  }),
  q({
    id: 'm-sw-3',
    title: 'Escaping closure and self',
    kind: 'Debug',
    prompt: `A manager stores \`var handler: (() -> Void)?\` and sets \`handler = { self.send() }\` in \`start()\`. \`deinit\` never runs. Fix it two ways.`,
    think: ['Who retains handler?', 'weak vs breaking the store'],
    solution: `\`[weak self]\` in the closure, **or** set \`handler = nil\` when stopping and do not store if you can use a delegate weakly. Both: cancel in stop().`,
    explanation: 'Stored escaping closures are ownership. Weak breaks the cycle; nil-ing is explicit lifetime.',
    tradeoffs: 'unowned if lifetimes are nested and proven — crashes in the wild more than it saves.',
    followups: [{ q: 'Does [weak self] cancel the work?', a: 'No. Also cancel the task/session.' }],
    teaches: ['Retain cycles', 'Escaping stores', 'Cancellation vs weak'],
  }),
  q({
    id: 'm-sw-4',
    title: 'mutating struct in a class',
    kind: 'Debug',
    prompt: `\`class Host { var s: Stats }\` and you pass \`host.s\` into a function \`func bump(_ s: Stats) { var x = s; x.n += 1 }\`. Host does not change. The author expected mutation. Explain and fix.`,
    think: ['Is Stats a struct?', 'Inout vs copy'],
    solution: `\`bump\` mutates a copy. Use \`func bump(_ s: inout Stats)\` and \`bump(&host.s)\`, or \`host.s.n += 1\`, or make Stats a class if identity is required.`,
    explanation: 'Value types do not remotely update the owner. inout is a write-back, not a pointer you stash.',
    pitfalls: 'Storing inout is illegal. Classes hide the bug until threads appear.',
    tradeoffs: 'Keep Stats a struct; mutate on the owner. Classes for identity (a live meter).',
    followups: [{ q: 'If bump is async?', a: 'You cannot inout across await. Mutate after await on the owner.' }],
    teaches: ['Value semantics', 'inout', 'Where mutation lives'],
  }),
  q({
    id: 'm-sw-5',
    title: 'Actor and non-Sendable capture',
    kind: 'Review',
    prompt: `\`Task { await actor.load(self.cache) }\` where \`cache\` is \`NSMutableDictionary\` on a UIViewController. Compiler warning in Swift 6. What is the real bug?`,
    think: ['Sendable', 'Who mutates cache?', 'MainActor'],
    solution: `NSMutableDictionary is not Sendable. Crossing into the actor is a data race. Isolate cache on MainActor, copy to a value \`[Key: Value]\` before hop, or move the cache into the actor.`,
    explanation: 'Swift 6 is telling you about Day 2 races. The warning is the bug.',
    tradeoffs: 'Copying a small dictionary is cheaper than debugging a race. Huge caches belong in one actor.',
    followups: [{ q: '@unchecked Sendable on the VC?', a: 'Lies to the compiler. Do not.' }],
    teaches: ['Sendable', 'Isolation', 'Copy then hop'],
  }),
  q({
    id: 'm-sw-6',
    title: 'Equatable synthesised wrong',
    kind: 'Debug',
    prompt: `A \`struct User: Hashable\` used in a Set includes a \`UUID()\` default field \`let nonce = UUID()\`. Set inserts never hit. Why?`,
    think: ['What is in Hashable synthesis?', 'Identity vs value'],
    solution: `Every instance has a unique nonce, so equality never holds. Exclude nonce from Hashable, or do not store a random field on a value you intend to dedupe.`,
    explanation: 'Synthesis includes all stored properties. Accidental identity fields break Set/Dictionary and SwiftUI identity if used as id.',
    tradeoffs: 'Explicit Hashable is more code and honest. UUID as id is correct for messages, wrong for "same user."',
    followups: [{ q: 'SwiftUI ForEach id?', a: 'Use stable user.id, not the struct’s synthesised hash.' }],
    teaches: ['Hashable synthesis', 'Identity fields', 'Sets'],
  }),
  q({
    id: 'm-sw-7',
    title: 'lazy var and thread safety',
    kind: 'Predict',
    difficulty: 'Expert',
    prompt: `\`lazy var formatter = DateFormatter()\` on a class used from URLSession callbacks and main. What can happen?`,
    think: ['Is lazy atomic?', 'DateFormatter thread safety'],
    solution: `lazy init is not atomic — two threads can init twice or race. DateFormatter is not thread-safe for mutation. Use a local formatter, a cached one on a serial queue, or \`FormatStyle\`.`,
    explanation: 'lazy is a local memo, not a singleton construct. Combine with an unsafe formatter and you get Heisenbugs (Day 6 production crash flavour).',
    testing: 'TSan soak. Unit tests will miss it.',
    tradeoffs: 'ISO8601DateFormatter on a dedicated actor is enough. Global static DateFormatter must be documented and isolated.',
    followups: [{ q: 'static let formatter?', a: 'Init once is safer; still isolate uses.' }],
    teaches: ['lazy races', 'DateFormatter', 'TSan'],
  }),
  q({
    id: 'm-sw-8',
    title: 'Result builder identity',
    kind: 'Review',
    prompt: `\`@ViewBuilder var body\` switches on enum with \`if\` without \`id\`. State in a child text field resets. Why?`,
    think: ['View identity', 'if vs switch'],
    solution: 'Structural identity changed: the branch is a different view tree position. Use a stable \`.id(user.id)\` on the editor, or keep the editor outside the if. Do not \`.id(UUID())\`.',
    explanation: 'SwiftUI identity is Day 3. Result builders assign identity by structure.',
    tradeoffs: 'Explicit ids when the tree is dynamic. Implicit structure when the tree is stable.',
    followups: [{ q: 'AnyView?', a: 'Erases identity and type; last resort.' }],
    teaches: ['View identity', 'ViewBuilder', 'State reset'],
  }),
  q({
    id: 'm-sw-9',
    title: 'weak delegate that is a struct',
    kind: 'Debug',
    prompt: `API is \`weak var delegate: Delegate?\` but Delegate is a struct. It will not compile. The engineer makes it a class "to make weak work." Review.`,
    think: ['Why is weak only for class?', 'Would a closure be better?'],
    solution: 'weak is ARC. Structs are not refcounted. Prefer a closure \`var onEvent: ((Event) -> Void)?\` with weak capture at the call site, or a class-bound protocol \`AnyObject\`. Do not invent a class just to satisfy weak if a callback is the interface.',
    explanation: 'Delegates are ownership APIs. Closures make capture explicit (Day 1).',
    tradeoffs: 'Class-bound protocol if many methods. Closures if one or two events.',
    followups: [{ q: 'unowned delegate?', a: 'Same crash profile as unowned self.' }],
    teaches: ['weak + AnyObject', 'Closures vs delegates'],
  }),
  q({
    id: 'm-sw-10',
    title: 'Copy-on-write that does not',
    kind: 'Predict',
    prompt: `You wrap \`[Int]\` in a class box without \`isKnownUniquelyReferenced\`. Two structs share the box; mutate one. What happens? How does Array itself avoid this?`,
    think: ['Unique reference', 'When does Array copy'],
    solution: 'Both see the mutation. Array’s buffer copies when the storage is not unique. Implement COW with isKnownUniquelyReferenced before mutating, or just store [Int] and let stdlib do it.',
    explanation: 'Day 1 40 MB copy. Do not reimplement Array poorly.',
    tradeoffs: 'Custom COW is for non-Array buffers (pixels, C). Otherwise use Array.',
    followups: [{ q: 'isKnownUniquelyReferenced on a protocol existential?', a: 'Needs a final class box. Existentials confuse uniqueness.' }],
    teaches: ['COW', 'isKnownUniquelyReferenced'],
  }),
]

const ios: Problem[] = [
  q({
    id: 'm-io-1',
    title: 'viewDidAppear firing twice',
    kind: 'Debug',
    prompt: 'Home logs analytics in viewDidAppear. Numbers are ~2× sessions. Containment and a nav controller are involved. What do you check?',
    think: ['Child VC appear', 'Interactive pop', 'Tab switch'],
    solution: 'Child + parent both appear. Also: interactive pop cancelled retriggers. Log in a dedicated tracker with a session id, or viewDidAppear with a flag, or analytics on "became visible to user" with a debounce. Do not fire from both container and child.',
    explanation: 'Lifecycle is not "screen shown once." It is a tree.',
    tradeoffs: 'A visibility tracker is more code and correct. A boolean is cheap and wrong under containment.',
    followups: [{ q: 'SwiftUI onAppear?', a: 'Same class of bug; identity and parent refreshes.' }],
    teaches: ['VC lifecycle', 'Containment', 'Analytics duplication'],
  }),
  q({
    id: 'm-io-2',
    title: 'Auto Layout loop',
    kind: 'Incident',
    prompt: 'Console: unsatisfiable constraints on a cell after rotate. Layout time spikes. How do you debug?',
    think: ['Which constraint conflicts?', 'Are you adding constraints in layoutSubviews?'],
    solution: 'Read the exception’s private UIKit log with identifiers on constraints. Do not add constraints every layoutSubviews — activate once. Use required vs hugging. Cells: content view, not cell itself, for constraints.',
    explanation: 'Unsatisfiable constraints are a layout bug, not a GPU bug. They cost CPU (Day 6).',
    testing: 'Rotate UI test. Instruments Time Profiler if it hitches.',
    tradeoffs: 'Frames in a performance cell can be valid. Do not mix freely with Auto Layout in the same view.',
    followups: [{ q: 'intrinsic size vs height constraint?', a: 'One source of height. Two required heights fight.' }],
    teaches: ['Auto Layout', 'Constraint identity', 'Cell layout'],
  }),
  q({
    id: 'm-io-3',
    title: 'Diffable crash: inconsistent snapshot',
    kind: 'Incident',
    prompt: 'Crash applying a snapshot while a previous apply is in flight. Two VMs update the same collection.',
    think: ['Serialise applies', 'Hash of items'],
    solution: 'One owner applies snapshots. Serial queue/actor. Identifiers must be Hashable stably (no UUID nonce). apply(animatingDifferences: false) on rapid updates if needed.',
    explanation: 'Diffable is not thread-safe theatre. It is a serial document.',
    tradeoffs: 'ReloadData is simpler and loses animation. Fine for a debug screen.',
    followups: [{ q: 'Hashable from mutable title?', a: 'ID is id, not display text.' }],
    teaches: ['Diffable', 'Serial UI updates', 'Stable IDs'],
  }),
  q({
    id: 'm-io-4',
    title: 'StateObject vs ObservedObject in a row',
    kind: 'Review',
    prompt: 'Each row does `@StateObject var vm = RowVM(id: id)` but `id` changes because the row is reused in a List. What happens?',
    think: ['StateObject lifetime', 'Reuse'],
    solution: 'StateObject keeps the first VM for that view identity. Reuse/identity mismatch shows the wrong row. Use a value Post in the row, or @Observable model keyed by id from the parent. Recreate identity with .id(post.id).',
    explanation: 'Ownership wrappers pin objects to identity. Reuse is identity’s enemy (Day 3).',
    tradeoffs: 'Parent-owned row models scale. Per-row StateObject is for true child screens, not cells.',
    followups: [{ q: 'UIKit cell equivalent?', a: 'configure(with:) every reuse, no leftover VM.' }],
    teaches: ['StateObject', 'List reuse', 'Row models'],
  }),
  q({
    id: 'm-io-5',
    title: 'UIKit SwiftUI child, keyboard issues',
    kind: 'Incident',
    prompt: 'UIHostingController in a UIKit form. Keyboard covers fields. Safe area looks wrong.',
    think: ['additionalSafeAreaInsets', 'keyboardIgnore'],
    solution: 'Hosting controller additionalSafeAreaInsets / sizing; avoid nested ScrollViews fighting. Prefer one scroll owner. keyboardAdaptive on the UIKit side or SwiftUI scrollDismissesKeyboard.',
    explanation: 'Interop is two layout systems. One must own the keyboard inset.',
    tradeoffs: 'A full SwiftUI screen is less glue. A representable field in UIKit may be less pain than hosting the world.',
    followups: [{ q: 'PreferredContentSize?', a: 'Needed for sheets; update when SwiftUI intrinsic size changes.' }],
    teaches: ['UIKit ↔ SwiftUI', 'Keyboard', 'Safe area'],
  }),
  q({
    id: 'm-io-6',
    title: 'Image in SwiftUI body',
    kind: 'Performance',
    prompt: '`Image(uiImage: UIImage(data: data)!)` inside a row body. Scroll hitches. Fix.',
    think: ['Decode on main', 'Allocation'],
    solution: 'Decode/downsample off main, cache UIImage sized to the row, pass the ready image in. Placeholder until then. Never decode in body.',
    explanation: 'body is for describing views, not JPEG decode (Days 2–3, 6).',
    tradeoffs: 'AsyncImage is convenient and still needs downsample for large assets.',
    followups: [{ q: 'UIImage.prepareForDisplay?', a: 'Good for UIKit path; still not in SwiftUI body synchronously.' }],
    teaches: ['Image decode', 'body purity'],
  }),
  q({
    id: 'm-io-7',
    title: 'Trait collection and dark mode flash',
    kind: 'Debug',
    prompt: 'Cached CGImages look wrong when switching to dark mode. Snapshot of Home is stale.',
    think: ['Asset catalog traits', 'Cache keys'],
    solution: 'Cache keys must include trait / color scheme, or use template images / dynamic colors. Invalidate cache on traitCollectionDidChange. Do not snapshot once in viewDidLoad.',
    explanation: 'Appearance is data. Caches that ignore traits are bugs.',
    tradeoffs: 'Two cache entries vs redraw. For icons, dynamic color is cheaper.',
    followups: [{ q: 'iPad split screen traits?', a: 'Traits can change without a full theme switch. Same invalidation.' }],
    teaches: ['Trait collections', 'Cache keys', 'Dark mode'],
  }),
  q({
    id: 'm-io-8',
    title: 'Background fetch vs BGTask',
    kind: 'Judgment',
    prompt: 'Product wants hourly silent sync. You have Background Fetch, BGAppRefreshTask, and a silent push. Pick and defend.',
    think: ['Budget', 'iOS version', 'User-visible'],
    solution: 'BGAppRefreshTask + opportunistic silent push if the server can. Background Fetch is legacy. Do not promise hourly — the system budgets. For user-visible work, BGProcessingTask with power constraints. Socket is not for killed apps.',
    explanation: 'Background is a negotiation with iOS, not a cron.',
    tradeoffs: 'Silent push is efficient and requires server. Refresh tasks are best-effort.',
    followups: [{ q: 'Expired task?', a: 'Stop, persist checkpoint, request again. Do not ignore expirationHandler.' }],
    teaches: ['BGTask', 'System budgets', 'Silent push'],
  }),
  q({
    id: 'm-io-9',
    title: 'Deep link while logged out',
    kind: 'Design',
    prompt: 'User opens `app://checkout/sku/42` cold, logged out. After login, they land on Home. How should a senior handle pending routes?',
    think: ['Where is the URL stored?', 'Who consumes it once?'],
    solution: 'A `PendingRoute` in an app coordinator, persisted if you must survive process death (disk, not only memory). After auth, consume once. Validate sku still exists. Do not let Home’s onAppear steal it.',
    explanation: 'Navigation is a queue, not a side effect of the last VC.',
    tradeoffs: 'In-memory pending is simpler if login cannot kill the process. Persist for universal links through Safari.',
    followups: [{ q: 'Multiple links?', a: 'Last wins or a stack — product call. Document it.' }],
    teaches: ['Coordinators', 'Auth gates', 'Deep links'],
  }),
  q({
    id: 'm-io-10',
    title: 'Accessibility on a custom control',
    kind: 'Review',
    prompt: 'A custom star rating is a row of UIViews with taps. VoiceOver reads "button button button". What do you implement?',
    think: ['UIAccessibility traits', 'value'],
    solution: 'One accessibility element for the control: trait adjustable, value "3 of 5", increment/decrement. Hide children. Or a UISlider analogue. Dynamic Type on the label.',
    explanation: 'Custom controls that ignore a11y fail senior bars even if the architecture is pretty.',
    tradeoffs: 'UISlider is less pretty and free. Custom means you own VoiceOver.',
    followups: [{ q: 'SwiftUI equivalent?', a: 'accessibilityValue + adjustable action; hide children.' }],
    teaches: ['VoiceOver', 'Adjustable traits', 'Hiding children'],
  }),
]

const concurrency: Problem[] = [
  q({
    id: 'm-co-1',
    title: 'TaskGroup vs async let',
    kind: 'Judgment',
    prompt: 'Load user, feed, and config. Sometimes config is optional. Which primitive, and how do you cancel?',
    think: ['Static vs dynamic child count', 'Failure policy'],
    solution: '`async let` for three known calls. TaskGroup if the set is dynamic. `try await` cancels siblings on throw if you want fail-fast; otherwise `try?` per child and merge. Cancel the parent on disappear (`.task`).',
    explanation: 'Structured concurrency is a tree of cancel. Unstructured Task is how Home outlives the screen.',
    tradeoffs: 'Fail-fast is simpler UX. Partial UI is kinder on flaky networks.',
    followups: [{ q: 'Priority?', a: 'Inherit unless you have a reason. Do not bump everything to user-initiated.' }],
    teaches: ['async let', 'TaskGroup', 'Cancel trees'],
  }),
  q({
    id: 'm-co-2',
    title: 'MainActor hop after URLSession',
    kind: 'Predict',
    prompt: 'nonisolated service returns `[Item]`. VM is @MainActor and assigns `items = await service.fetch()`. Where does decode run?',
    think: ['Isolation of fetch', 'Hop points'],
    solution: 'Decode runs in the service’s isolation (hopefully not main). Assignment runs on MainActor. If fetch is accidentally @MainActor, decode is on main — Day 2 hitch.',
    explanation: 'Know the hop. Annotate the service explicitly.',
    tradeoffs: 'A parser actor vs Task.detached. Prefer structured isolation over detached.',
    followups: [{ q: 'Sendable Item?', a: 'Required to hop the array across actors in Swift 6.' }],
    teaches: ['Isolation hops', 'MainActor', 'Sendable'],
  }),
  q({
    id: 'm-co-3',
    title: 'Continuation resumed twice',
    kind: 'Debug',
    prompt: 'A wrapper around a completion API uses withCheckedContinuation. The SDK sometimes calls completion twice. Production crash. Fix.',
    think: ['Resume once', 'Checked vs unsafe'],
    solution: 'A flag or `CheckedContinuation` stored in an atomic/optional; resume once, ignore extra. Prefer APIs that are already async. Unsafe continuations hide the bug until crash.',
    explanation: 'Day 6 production crash. Continuations are one-shot.',
    testing: 'Fake SDK that double-completes; assert no crash and one resume.',
    tradeoffs: 'Checked is slower and correct. Always in app code.',
    followups: [{ q: 'Cancel?', a: 'withTaskCancellationHandler to cancel the SDK work; resume with CancellationError once.' }],
    teaches: ['Continuations', 'One-shot resume', 'Bridging'],
  }),
  q({
    id: 'm-co-4',
    title: 'Actor reentrancy in a cache',
    kind: 'Predict',
    prompt: '`actor Cache { func get(_ k: Key) async -> Value { if let v = map[k] { return v }; let v = await load(k); map[k] = v; return v } }` Two calls, same key, load is slow. How many loads?',
    think: ['Await interleaving', 'Single-flight'],
    solution: 'Two loads. Same as token refresh without join. Store `Task<Value, Error>` in the map for in-flight keys.',
    explanation: 'Actors + await ≠ mutex across the await (Day 2 wallet, Day 5 refresh).',
    tradeoffs: 'Single-flight tasks cost a dictionary of Tasks. Worth it for network. Not for in-memory math.',
    followups: [{ q: 'Cancellation of one waiter?', a: 'Do not cancel the shared load; waiters drop. Or refcount waiters.' }],
    teaches: ['Reentrancy', 'Single-flight', 'Caches'],
  }),
  q({
    id: 'm-co-5',
    title: 'GCD and actors mixed',
    kind: 'Review',
    prompt: 'Legacy code `DispatchQueue.global().async { self.items.append }` plus a new actor mutating items. Is TSan enough?',
    think: ['Two isolation domains', 'Sendable'],
    solution: 'Pick one domain. Migrate appends into the actor or a serial queue, not both. TSan helps if you can run it; Swift 6 isolation is the design fix.',
    explanation: 'Two worlds is still a race.',
    tradeoffs: 'A serial queue wrapper during migration. Then delete GCD for that type.',
    followups: [{ q: 'Main thread checker vs TSan?', a: 'MTC is UIKit on main. TSan is races. You often need both.' }],
    teaches: ['GCD vs actors', 'TSan', 'Migration'],
  }),
]

const debugging: Problem[] = [
  q({
    id: 'm-db-1',
    title: 'Cold launch 4 seconds',
    kind: 'Performance',
    prompt: 'How do you investigate a 4 s cold launch on a mid-tier iPhone? What is in-budget vs vanity?',
    think: ['Before main', 'First frame', 'Home data'],
    solution: 'Time Profiler + launching instrument / os_signpost: +load/static, didFinishLaunching, first layout, first network. Move work after first frame. Do not decode fonts/images/JSON in AppDelegate. 4 s is not "SwiftUI." Measure main vs process create.',
    explanation: 'Launch is a budget. Home’s 2 s hitch is a different budget (Day 6).',
    tradeoffs: 'Eager SDKs vs first pixel. Defer analytics. Legal SDKs may be forced — isolate them.',
    followups: [{ q: 'Prewarming?', a: 'iOS may prewarm; do not put side effects in static inits that assume a full launch.' }],
    teaches: ['Launch budget', 'Defer work', 'Instruments'],
  }),
  q({
    id: 'm-db-2',
    title: 'Main Thread Checker hit',
    kind: 'Incident',
    prompt: 'UIView.bounds from a URLSession callback. App "usually works." What do you do besides move the line?',
    think: ['Why it worked', 'Hidden cousins'],
    solution: 'Hop to MainActor for UI. Audit the whole callback: model mutation might belong in an actor, UI in main. Add the checker in a scheme. Search for other UIKit in completions.',
    explanation: 'Usually works is data races on UIKit internals.',
    tradeoffs: 'Marking the VM @MainActor is a blunt fix that can put decode on main — split.',
    followups: [{ q: 'UIImage in callback?', a: 'UIImage init is often OK off main; assigning to imageView is not.' }],
    teaches: ['Main Thread Checker', 'Callback isolation'],
  }),
  q({
    id: 'm-db-3',
    title: 'LLDB: object is alive, you do not know why',
    kind: 'Incident',
    prompt: 'A VC should have deallocated. How do you ask the runtime who retains it?',
    think: ['Memory Graph', 'po', 'breakpoints in dealloc'],
    solution: 'Debug Memory Graph, search the class, look at incoming refs. `leaks` / Allocations generations. Temporary `deinit { print }` in DEBUG. Do not guess [weak self] everywhere without a graph.',
    explanation: 'Ownership is visible. Guessing is junior.',
    tradeoffs: 'Logging deinit is cheap. Graph is truth.',
    followups: [{ q: 'Release build?', a: 'MetricKit / Allocations on TestFlight. dSYMs.' }],
    teaches: ['Memory Graph', 'Allocations', 'deinit logs'],
  }),
  q({
    id: 'm-db-4',
    title: 'Flaky UI test on CI only',
    kind: 'Incident',
    prompt: 'Login UI test fails 20% on CI, never locally. Timeouts waiting for a button.',
    think: ['Speed', 'Animations', 'Network', 'Main hop'],
    solution: 'Stub network; disable animations; wait on existence not sleep; CI simulator is slower/colder. Bound waits. Make the app inject a fake clock/session in UI-test launch arguments. Record the failure video.',
    explanation: 'Flakes are races. Sleeping longer hides them until CI is worse.',
    tradeoffs: 'More injection for UI tests vs brittle real-network tests. Inject.',
    followups: [{ q: 'Parallel simulators?', a: 'No shared Keychain/simulator state. Unique data per test.' }],
    teaches: ['UI test flakes', 'Launch arguments', 'No sleep'],
  }),
  q({
    id: 'm-db-5',
    title: 'Thread Sanitizer red on a Combine pipeline',
    kind: 'Debug',
    prompt: 'receive(on:) is missing; a @Published is written from a background scheduler. Fix and say when to use actors instead.',
    think: ['Publisher thread', 'MainActor'],
    solution: '`receive(on: DispatchQueue.main)` or `MainActor.assumeIsolated` / `.receive(on: RunLoop.main)` before assign. Better: make the VM @MainActor and use async sequences. TSan is right.',
    explanation: '@Published is not a queue. You chose the scheduler.',
    tradeoffs: 'Combine + actors is two systems. Migrating a pipeline is fine; do not mix per line.',
    followups: [{ q: 'subscribe(on:)?', a: 'Where subscription work runs, not where UI assign runs. People confuse them.' }],
    teaches: ['TSan', 'Combine schedulers', '@Published'],
  }),
]

const architecture: Problem[] = [
  q({
    id: 'm-ar-1',
    title: 'Where does navigation live?',
    kind: 'Architecture',
    prompt: 'SwiftUI NavigationStack vs coordinator vs router object. An app with 80 screens, mixed UIKit. Pick a policy.',
    think: ['Who can unit-test a flow?', 'Deep links'],
    solution: 'A routing type at the composition root that UIKit and SwiftUI both call. NavigationStack path for SwiftUI subtrees. Do not let each VM push. Policy: features emit intents.',
    explanation: 'Day 4. Navigation is app policy, not a button.',
    tradeoffs: 'Pure SwiftUI NavigationStack is enough under ~15 screens with no UIKit. Mixed apps need an explicit router.',
    followups: [{ q: 'Environment(\\.router)?', a: 'OK if it is a protocol, not a god object.' }],
    teaches: ['Routers', 'Intents', 'Mixed stacks'],
  }),
  q({
    id: 'm-ar-2',
    title: 'Repository that is a second VM',
    kind: 'Review',
    prompt: 'UserRepository is 1 200 lines, @MainActor, holds UI strings, calls analytics, and fetches. Critique.',
    think: ['SRP', 'Where UI strings belong'],
    solution: 'Split: HTTP client, mapping, optional cache, analytics at the use-case or UI edge. Repository returns User, not "Welcome, \(name)". Not @MainActor unless it is UI state.',
    explanation: 'The name Repository does not confer architecture.',
    tradeoffs: 'A thin repository is a cache+API. When it grows UI, it is a VM.',
    followups: [{ q: 'One repository per endpoint?', a: 'Per aggregate. User, not GetUser and GetAvatar.' }],
    teaches: ['SRP', 'Repository scope', 'MainActor placement'],
  }),
  q({
    id: 'm-ar-3',
    title: 'Feature flag SDK in every VM',
    kind: 'Architecture',
    prompt: 'Twelve VMs import LaunchDarkly. Tests boot the SDK. How do you invert this?',
    think: ['Protocol', 'Defaults in tests'],
    solution: '`protocol Flagging { func enabled(FlagKey) -> Bool }` with a live adapter and `StaticFlags` in tests. Composition root configures the SDK once.',
    explanation: 'Same DI as HTTP. SDKs are infrastructure.',
    tradeoffs: 'A flags enum prevents stringly keys. Worth it at 12 call sites.',
    followups: [{ q: 'Async flags?', a: 'Expose async or a stream; VMs should not poll the SDK.' }],
    teaches: ['DI', 'SDK boundaries', 'Test doubles'],
  }),
  q({
    id: 'm-ar-4',
    title: 'Modularize or not',
    kind: 'Judgment',
    prompt: 'Team of four, one app, 40 screens, 3 minute CI. A new hire wants 20 SPM packages. Your call?',
    think: ['Compile vs ceremony', 'Team size'],
    solution: 'No. Folders + boundaries + one or two packages if a compile hotspot appears. 20 packages is org-scale (Day 7). Revisit at 10+ engineers or 15 min CI.',
    explanation: 'Overengineering is an architecture answer. Seniors say no.',
    tradeoffs: 'A DesignSystem package can still be worth it for a second target (widget).',
    followups: [{ q: 'What boundary without packages?', a: 'No UIKit in stores; no URLSession in views; PR review.' }],
    teaches: ['YAGNI modules', 'Team scale', 'Boundaries without SPM'],
  }),
  q({
    id: 'm-ar-5',
    title: 'Offline-first vs cache-aside',
    kind: 'Architecture',
    prompt: 'Settings vs chat vs feed. Which persistence strategy per surface?',
    think: ['Can we delete the store?', 'Conflict'],
    solution: 'Settings: server truth, tiny cache. Feed: stale-while-revalidate, disposable. Chat: local truth + sync (Day 7). Do not SwiftData the feed just because chat needed it.',
    explanation: 'Persistence is a product property.',
    tradeoffs: 'One stack is simpler and wrong. Two stacks (cache files + a real DB) is normal.',
    followups: [{ q: 'UserDefaults for chat drafts?', a: 'No. Size and type. Use the chat store.' }],
    teaches: ['Persistence choice', 'Disposable vs durable'],
  }),
]

const system: Problem[] = [
  q({
    id: 'm-sy-1',
    title: 'Offline-first chat (combined)',
    kind: 'Design',
    difficulty: 'Expert',
    prompt: 'Design an offline-first chat client using Swift concurrency, actors, SwiftUI, local persistence, WebSockets, and DI. You have 25 minutes. What do you draw first?',
    think: ['Store as truth', 'Socket owner', 'Optimistic IDs', 'Cancel and leaks'],
    solution: 'Same as Day 7 problem 1, compressed: session-owned Realtime actor, MessageRepository actor, MainActor snapshots for SwiftUI, client UUID optimistic rows, single-flight auth, DI at composition root, cancel on logout. Cut typing/media for time; say so.',
    explanation: 'Interviewers watch whether you start with a god VC or a store. Start with data flow. Mention testing fakes. Mention Memory Graph for the socket.',
    internals: 'UI → Store → Repository → {DB, WS, REST}. Arrows inward.',
    testing: 'Repository fakes: ack, dup, gap fill. UI: send offline.',
    pitfalls: 'Designing the bubble UI first. Ignoring idempotency.',
    alternatives: 'Third-party chat SDK with an adapter if chat is not the product.',
    tradeoffs: 'This is appropriate for a chat product. It is overkill for a support web-view.',
    followups: [
      { q: 'How do you prove no leak when leaving a thread?', a: 'Memory Graph + cancel socket subscriptions scoped to conversation, not process, unless you still need inbox live.' },
      { q: 'SwiftUI list of 50k messages?', a: 'Windowed query, not load all. Identity by message id.' },
    ],
    teaches: ['System design', 'Combining the week', 'Scoping v1'],
  }),
  q({
    id: 'm-sy-2',
    title: 'Consumer app platform (combined)',
    kind: 'Architecture',
    difficulty: 'Expert',
    prompt: '40 engineers, weekly train, EU, crash-free goal. How do you organise iOS so checkout can ship in six weeks without a rewrite? Include CI and observability.',
    think: ['Strangler', 'Platform roads', 'Flags', 'What not to standardise'],
    solution: 'Day 4 strangler for checkout + Day 7 platform: HTTP/auth/flags/design/crash as roads. Feature modules acyclic. Weekly train + flags. CI on affected modules. MetricKit + dSYMs. Refuse 20 reactive frameworks.',
    explanation: 'Staff design is constraints. Name the first vertical, the platform, and the release valve.',
    testing: 'Checkout fakes + one smoke UI test on the train. Nightly 401-storm.',
    pitfalls: 'Rewrite proposal. Big-bang SPM. No flags.',
    alternatives: 'Outsource payments SDK with an adapter if that is faster — still invert it.',
    tradeoffs: 'Platform tax vs six-week checkout. You pay the tax on the roads, not on VIPER for settings.',
    followups: [
      { q: 'Who owns the token refresher?', a: 'Platform. Features never call /refresh.' },
      { q: 'How do you stop 3 000-line VCs from returning?', a: 'Review bar on the new feature; linters for URLSession in UI; time, not a slide.' },
    ],
    teaches: ['Staff architecture', 'Release trains', 'Platform vs feature'],
  }),
]

export const mockInterview = {
  id: 'mock',
  title: 'Senior iOS mock interview',
  kicker: 'Answer first',
  intro:
    'Work a section like a real loop. The problem and the think list are visible. Reveal only after you have an answer — out loud if you can. Then read expected answer, explanation, follow-ups, and how a senior is scored.',
  sections: [
    { id: 'swift', title: 'Swift', countLabel: '10 problems', problems: swift },
    { id: 'ios', title: 'iOS', countLabel: '10 problems', problems: ios },
    { id: 'concurrency', title: 'Concurrency', countLabel: '5 problems', problems: concurrency },
    { id: 'debugging', title: 'Debugging', countLabel: '5 scenarios', problems: debugging },
    { id: 'architecture', title: 'Architecture', countLabel: '5 questions', problems: architecture },
    { id: 'system', title: 'System design', countLabel: '2 problems', problems: system },
  ] satisfies MockSection[],
}
